/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Classes.main_class;
import Classes.register_users;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.nio.file.Paths;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.Login;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.*;
/**
 *
 * @author saimo
 */
public class Register extends javax.swing.JPanel {
    

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        PanelRegister = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UsernameText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        PasswordText = new javax.swing.JPasswordField();
        PasswordTextVisible = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(73, 80, 87));
        jLabel10.setText("Password");

        setPreferredSize(new java.awt.Dimension(450, 490));

        PanelRegister.setBackground(new java.awt.Color(84, 110, 230));
        PanelRegister.setName(""); // NOI18N
        PanelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 80, 87));
        jLabel1.setText("Confirm Password");
        PanelRegister.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Avatar2-fondoBlanco-100.png"))); // NOI18N
        PanelRegister.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 110));

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(73, 80, 87));
        jLabel6.setText("Username");
        PanelRegister.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        UsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextActionPerformed(evt);
            }
        });
        PanelRegister.add(UsernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 390, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salir-redondeado-24.png"))); // NOI18N
        jButton2.setText("Exit");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelRegister.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 80, 30));

        jButton1.setBackground(new java.awt.Color(85, 110, 230));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelRegister.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 280, 40));

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(73, 80, 87));
        jLabel7.setText("Password");
        PanelRegister.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, -1));

        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });
        PasswordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordTextKeyPressed(evt);
            }
        });
        PanelRegister.add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 390, 40));

        PasswordTextVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextVisibleActionPerformed(evt);
            }
        });
        PanelRegister.add(PasswordTextVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 390, 40));

        jLabel4.setBackground(new java.awt.Color(58, 61, 65));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Card_Content.png"))); // NOI18N
        jLabel4.setText("dw");
        PanelRegister.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 450, -1));

        jLabel11.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Register ");
        PanelRegister.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sign up to continue");
        PanelRegister.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, -1));

        jTextField3.setText("jTextField3");
        PanelRegister.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 390, 40));

        jLabel13.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(73, 80, 87));
        jLabel13.setText("Password");
        PanelRegister.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void UsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseExited
    /**
    * Este método sirve para agregar un usuario a la base de datos
    * @author saimo
    */
    private void Add_user() {
        String archive = Paths.get("src", "DataBase", "usuarios.csv").toString();
        FileWriter fw = null;
        PrintWriter pw = null;
        
        try{ 
            fw = new FileWriter(archive);
            pw = new PrintWriter(fw);
            for(register_users i: main_class.users){
                String line = i.getUsername() + "," + i.getPassword() + "," + i.getRemember();
                pw.println(line);
            }
            
        }catch (Exception ex) {
            ex.printStackTrace();
        }
        finally{
            try{
                if(fw != null){
                    fw.close();
            }
            }catch(Exception ex){
                    ex.printStackTrace();
            }      
        }
    }
    /**
    * Este método sirve para crear un nuevo usuario
    * @author saimo
    */
    private boolean create_user() {
        
        String create_username;
        String create_password;
        boolean create_remember;
        Boolean register = false;
        

        create_username = String.valueOf(UsernameText.getText());
        String username = UsernameText.getText();
        if (username == null || username.length() < 4) {
            JOptionPane.showMessageDialog(this, "Enter a valid username greater than or equal to 4 characters");
            return false;
        }
        String password = PasswordTextVisible.getText();
        if (password.isEmpty() || password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Enter a valid password greater than or equal to 8 characters");
            return false;
        }
        if (password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Enter a valid password greater than or equal to 8 characters");
            return false;
        }
        if (!PasswordTextVisible.getText().equals(String.valueOf(PasswordText.getPassword()))) {
            JOptionPane.showMessageDialog(this,"Password Is Different");
            return false;
        }
        create_password = String.valueOf(PasswordTextVisible.getText());
        create_remember = false;

        for(register_users A: main_class.users){
            if(A.getUsername().equals(create_username)){
                register = true;
                break;}         
            }

            if(register){
                JOptionPane.showMessageDialog(this,"This Username Already Exists ");  
                return false;
            }else{
                register_users user = new register_users();
                user.setUsername(create_username);
                user.setPassword(create_password);
                user.setRemember(create_remember);
                main_class.users.add(user);
                
                Add_user();
                JOptionPane.showMessageDialog(this, "User Added Successfully");

            }
        return true;
    }
    /**
    * Este evento detecta si fue presionado el boton de register para registrar un nuevo usuario en la base de datos
    * @author saimo
    * 
    */
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean result = create_user();
        if (result) {
            UsernameText.setText("");
            PasswordTextVisible.setText("");
            PasswordText.setText("");
            Login.hideRegisterPanel();
            Login.showLoginPanel();
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    private void PasswordTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextKeyPressed

    private void PasswordTextVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextVisibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextVisibleActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setForeground(Color.GRAY);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salir-redondeado-24GIF.gif")));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setForeground(Color.black);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salir-redondeado-24.png")));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UsernameText.setText("");
        PasswordTextVisible.setText("");
        PasswordText.setText("");
        Login.hideRegisterPanel();
        Login.showLoginPanel();
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    public void ShowJPanel(JPanel p, JPanel main){
        p.setSize(450, 490);
        p.setLocation(440,110);
        main.add(p, new AbsoluteConstraints(440, 110, 450, 490));
        main.setComponentZOrder(p, 0);
        main.revalidate();
        main.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelRegister;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JTextField PasswordTextVisible;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

  
}
