/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Classes.customer_class;
import Classes.item_class;
import Classes.maintenance_class;
import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 * Billing Screen
 * @author jonns
 * 
 */
public class ScreenBilling extends javax.swing.JPanel {

    /**
     * Creates new form ScreenMaintenance
     */
    public ScreenBilling() {
        initComponents();
        ReadCustomers();
        ReadItems();
        //ReadMaintenance();
        createIdsItems();
        //createIdsMaintenance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BillingView = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BillingWindowTitle = new javax.swing.JLabel();
        BillingWindowSubtitle = new javax.swing.JLabel();
        BillingAddButton = new javax.swing.JButton();
        BillingSearchButton = new javax.swing.JButton();
        BillingRevokeButton = new javax.swing.JButton();
        BillingInputPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ItemBillIdText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ItemBillSubtotalText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ItemCustomerIdCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ItemReceivementDayText = new javax.swing.JTextField();
        ItemReceivementMonthCombo = new javax.swing.JComboBox<>();
        ItemReceivementYearText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ItemBillStateCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ItemBillTaxText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ItemBillTotalText = new javax.swing.JTextField();
        ItemAcceptButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ItemOptionCombo = new javax.swing.JComboBox<>();
        ItemSearchButton = new javax.swing.JButton();
        BillingInputPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        MaintenanceBillIdText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        MaintenanceBillSubtotalText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        MaintenanceCustomerIdCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        MaintenanceReceivementDayText = new javax.swing.JTextField();
        MaintenanceReceivementMonthCombo = new javax.swing.JComboBox<>();
        MaintenanceReceivementYearText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        MaintenanceBillStateCombo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        MaintenanceBillTaxText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        MaintenanceBillTotalText = new javax.swing.JTextField();
        MaintenanceAcceptButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        MaintenanceOptionCombo = new javax.swing.JComboBox<>();
        MaintenanceSearchButton = new javax.swing.JButton();
        BillingWindowTitle1 = new javax.swing.JLabel();
        BillingWindowTitle2 = new javax.swing.JLabel();
        BillingCancelButton = new javax.swing.JButton();

        BillingView.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SalirView.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BillingWindowTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BillingWindowTitle.setText("Billing");

        BillingWindowSubtitle.setText("Select the action to perform");

        BillingAddButton.setText("Add Bill");
        BillingAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingAddButtonActionPerformed(evt);
            }
        });

        BillingSearchButton.setText("Search Bill");
        BillingSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingSearchButtonActionPerformed(evt);
            }
        });

        BillingRevokeButton.setText("Revoke Bill");
        BillingRevokeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingRevokeButtonActionPerformed(evt);
            }
        });

        BillingInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Bill Id:");

        ItemBillIdText.setEnabled(false);

        jLabel2.setText("Bill Subtotal:");

        ItemBillSubtotalText.setEnabled(false);

        jLabel3.setText("Customer:");

        ItemCustomerIdCombo.setEnabled(false);
        ItemCustomerIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCustomerIdComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Receivement Date:");

        ItemReceivementDayText.setText("01");
        ItemReceivementDayText.setEnabled(false);

        ItemReceivementMonthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        ItemReceivementMonthCombo.setEnabled(false);
        ItemReceivementMonthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemReceivementMonthComboActionPerformed(evt);
            }
        });

        ItemReceivementYearText.setText("1900");
        ItemReceivementYearText.setEnabled(false);

        jLabel5.setText("Bill State:");

        ItemBillStateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Valid", "Revoked" }));
        ItemBillStateCombo.setEnabled(false);

        jLabel6.setText("Bill Tax:");

        ItemBillTaxText.setEnabled(false);
        ItemBillTaxText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBillTaxTextActionPerformed(evt);
            }
        });

        jLabel7.setText("Bill Total:");

        ItemBillTotalText.setEnabled(false);
        ItemBillTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBillTotalTextActionPerformed(evt);
            }
        });

        ItemAcceptButton.setText("Accept");
        ItemAcceptButton.setEnabled(false);

        jLabel8.setText("Option:");

        ItemOptionCombo.setEnabled(false);
        ItemOptionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemOptionComboActionPerformed(evt);
            }
        });

        ItemSearchButton.setText("S");
        ItemSearchButton.setEnabled(false);

        javax.swing.GroupLayout BillingInputPanelLayout = new javax.swing.GroupLayout(BillingInputPanel);
        BillingInputPanel.setLayout(BillingInputPanelLayout);
        BillingInputPanelLayout.setHorizontalGroup(
            BillingInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillingInputPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(BillingInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingInputPanelLayout.createSequentialGroup()
                        .addComponent(ItemSearchButton)
                        .addGap(18, 18, 18)
                        .addGroup(BillingInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BillingInputPanelLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel1))
                            .addGroup(BillingInputPanelLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel4))
                            .addGroup(BillingInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ItemBillTaxText)
                                .addComponent(ItemBillIdText)
                                .addComponent(ItemCustomerIdCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(BillingInputPanelLayout.createSequentialGroup()
                                    .addComponent(ItemReceivementDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ItemReceivementMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(ItemReceivementYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ItemBillStateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ItemBillSubtotalText)
                                .addComponent(ItemBillTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BillingInputPanelLayout.createSequentialGroup()
                                    .addGap(140, 140, 140)
                                    .addComponent(jLabel8))
                                .addComponent(ItemOptionCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BillingInputPanelLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel5))
                            .addGroup(BillingInputPanelLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jLabel2))
                            .addGroup(BillingInputPanelLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel6))
                            .addGroup(BillingInputPanelLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel7))
                            .addGroup(BillingInputPanelLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel3)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingInputPanelLayout.createSequentialGroup()
                        .addComponent(ItemAcceptButton)
                        .addGap(160, 160, 160))))
        );
        BillingInputPanelLayout.setVerticalGroup(
            BillingInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillingInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BillingInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemOptionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemSearchButton))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemBillIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemCustomerIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BillingInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemReceivementDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemReceivementMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemReceivementYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemBillStateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemBillSubtotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemBillTaxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemBillTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ItemAcceptButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        BillingInputPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Bill Id:");

        MaintenanceBillIdText.setEnabled(false);

        jLabel10.setText("Bill Subtotal:");

        MaintenanceBillSubtotalText.setEnabled(false);

        jLabel11.setText("Customer:");

        MaintenanceCustomerIdCombo.setEnabled(false);
        MaintenanceCustomerIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceCustomerIdComboActionPerformed(evt);
            }
        });

        jLabel12.setText("Receivement Date:");

        MaintenanceReceivementDayText.setText("01");
        MaintenanceReceivementDayText.setEnabled(false);

        MaintenanceReceivementMonthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        MaintenanceReceivementMonthCombo.setEnabled(false);
        MaintenanceReceivementMonthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceReceivementMonthComboActionPerformed(evt);
            }
        });

        MaintenanceReceivementYearText.setText("1900");
        MaintenanceReceivementYearText.setEnabled(false);

        jLabel13.setText("Bill State:");

        MaintenanceBillStateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Valid", "Revoked" }));
        MaintenanceBillStateCombo.setEnabled(false);

        jLabel14.setText("Bill Tax:");

        MaintenanceBillTaxText.setEnabled(false);
        MaintenanceBillTaxText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceBillTaxTextActionPerformed(evt);
            }
        });

        jLabel15.setText("Bill Total:");

        MaintenanceBillTotalText.setEnabled(false);
        MaintenanceBillTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceBillTotalTextActionPerformed(evt);
            }
        });

        MaintenanceAcceptButton.setText("Accept");
        MaintenanceAcceptButton.setEnabled(false);

        jLabel16.setText("Option:");

        MaintenanceOptionCombo.setEnabled(false);
        MaintenanceOptionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceOptionComboActionPerformed(evt);
            }
        });

        MaintenanceSearchButton.setText("S");
        MaintenanceSearchButton.setEnabled(false);

        javax.swing.GroupLayout BillingInputPanel1Layout = new javax.swing.GroupLayout(BillingInputPanel1);
        BillingInputPanel1.setLayout(BillingInputPanel1Layout);
        BillingInputPanel1Layout.setHorizontalGroup(
            BillingInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(BillingInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingInputPanel1Layout.createSequentialGroup()
                        .addComponent(MaintenanceSearchButton)
                        .addGap(18, 18, 18)
                        .addGroup(BillingInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel9))
                            .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel12))
                            .addGroup(BillingInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(MaintenanceBillTaxText)
                                .addComponent(MaintenanceBillIdText)
                                .addComponent(MaintenanceCustomerIdCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                                    .addComponent(MaintenanceReceivementDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(MaintenanceReceivementMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(MaintenanceReceivementYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(MaintenanceBillStateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MaintenanceBillSubtotalText)
                                .addComponent(MaintenanceBillTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                                    .addGap(140, 140, 140)
                                    .addComponent(jLabel16))
                                .addComponent(MaintenanceOptionCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel13))
                            .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jLabel10))
                            .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel14))
                            .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel15))
                            .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel11)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingInputPanel1Layout.createSequentialGroup()
                        .addComponent(MaintenanceAcceptButton)
                        .addGap(159, 159, 159))))
        );
        BillingInputPanel1Layout.setVerticalGroup(
            BillingInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillingInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BillingInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaintenanceOptionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaintenanceSearchButton))
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaintenanceBillIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaintenanceCustomerIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BillingInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaintenanceReceivementDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaintenanceReceivementMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaintenanceReceivementYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaintenanceBillStateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaintenanceBillSubtotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaintenanceBillTaxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaintenanceBillTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MaintenanceAcceptButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BillingWindowTitle1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BillingWindowTitle1.setText("Maintenance Billing");

        BillingWindowTitle2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BillingWindowTitle2.setText("Item Billing");

        BillingCancelButton.setText("Cancel");
        BillingCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BillingViewLayout = new javax.swing.GroupLayout(BillingView);
        BillingView.setLayout(BillingViewLayout);
        BillingViewLayout.setHorizontalGroup(
            BillingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillingViewLayout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addGroup(BillingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BillingViewLayout.createSequentialGroup()
                        .addComponent(BillingAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BillingSearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BillingRevokeButton)
                        .addGap(389, 389, 389))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingViewLayout.createSequentialGroup()
                        .addComponent(BillingCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BillingInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(BillingViewLayout.createSequentialGroup()
                        .addGroup(BillingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BillingViewLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(BillingWindowSubtitle))
                            .addGroup(BillingViewLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(BillingWindowTitle)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingViewLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(BillingWindowTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BillingWindowTitle1)
                .addGap(125, 125, 125))
            .addGroup(BillingViewLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BillingInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BillingViewLayout.setVerticalGroup(
            BillingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingViewLayout.createSequentialGroup()
                .addGroup(BillingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BillingViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BillingViewLayout.createSequentialGroup()
                        .addComponent(BillingWindowTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BillingWindowSubtitle)
                        .addGap(18, 18, 18)
                        .addGroup(BillingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BillingSearchButton)
                            .addComponent(BillingAddButton)
                            .addComponent(BillingRevokeButton))))
                .addGroup(BillingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BillingViewLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(BillingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BillingWindowTitle1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BillingWindowTitle2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BillingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BillingInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BillingInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingViewLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BillingCancelButton)
                        .addGap(8, 8, 8)))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BillingView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BillingView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        borrarPanel(new ScreenProducts());
        ShowJPanel(new ScreenMain());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SalirView2.png")));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SalirView.png")));
    }//GEN-LAST:event_jButton1MouseExited

    private void ItemCustomerIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCustomerIdComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemCustomerIdComboActionPerformed

    private void ItemBillTaxTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBillTaxTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemBillTaxTextActionPerformed

    private void ItemBillTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBillTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemBillTotalTextActionPerformed

    private void BillingAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingAddButtonActionPerformed
        String[] options = {"Item", "Maintenance"};
        int selection = JOptionPane.showOptionDialog(null, "Choose a Billing Option:", "BILLING", 0, 3, null, options, options[0]);
        switch(selection){
            case 0:
                ItemOptionCombo.setEnabled(true);
                createIdsItems();
            
            case 1:
                ItemOptionCombo.setEnabled(true);
                createIdsMaintenance();
        }   

        //Switch Flags
        BillAddFlag = true;
        BillSearchFlag = false;
        BillRevokeFlag = false;
        
        //Enable Buttons
        ItemCustomerIdCombo.setEnabled(true);
        ItemReceivementDayText.setEnabled(true);
        ItemReceivementMonthCombo.setEnabled(true);
        ItemReceivementYearText.setEnabled(true);
        ItemBillSubtotalText.setEnabled(true);
        ItemBillTaxText.setEnabled(true);
        ItemBillTotalText.setEnabled(true);
        ItemBillStateCombo.setSelectedIndex(0);
        
        BillingAddButton.setEnabled(false);
        BillingSearchButton.setEnabled(false);
        BillingRevokeButton.setEnabled(false);
        
        
    }//GEN-LAST:event_BillingAddButtonActionPerformed

    private void ItemReceivementMonthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemReceivementMonthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemReceivementMonthComboActionPerformed

    private void BillingSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingSearchButtonActionPerformed
        //Switch Flags
        BillAddFlag = false;
        BillSearchFlag = true;
        BillRevokeFlag = false;
        
        String[] options = {"Bill Id", "Date", "Customer Name"};
        int selection = JOptionPane.showOptionDialog(null, "Choose a Searching Option:", "SEARCH", 0, 3, null, options, options[0]);
        switch(selection){
            case 0:
                ItemBillIdText.setEnabled(true);
                
                BillingAddButton.setEnabled(false);
                BillingSearchButton.setEnabled(false);
                BillingRevokeButton.setEnabled(false);
                break;
            case 1:
                ItemReceivementDayText.setEnabled(true);
                ItemReceivementMonthCombo.setEnabled(true);
                ItemReceivementYearText.setEnabled(true);
                
                BillingAddButton.setEnabled(false);
                BillingSearchButton.setEnabled(false);
                BillingRevokeButton.setEnabled(false);
                break;
            case 2:
                ItemCustomerIdCombo.setEnabled(true);
                
                BillingAddButton.setEnabled(false);
                BillingSearchButton.setEnabled(false);
                BillingRevokeButton.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_BillingSearchButtonActionPerformed

    private void BillingRevokeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingRevokeButtonActionPerformed
        //Switch Flags
        BillAddFlag = false;
        BillSearchFlag = false;
        BillRevokeFlag = true;
        ItemBillStateCombo.setSelectedIndex(1);
        
        ItemBillIdText.setEnabled(true);
        
        BillingAddButton.setEnabled(false);
        BillingSearchButton.setEnabled(false);
        BillingRevokeButton.setEnabled(false);
    }//GEN-LAST:event_BillingRevokeButtonActionPerformed

    private void ItemOptionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemOptionComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemOptionComboActionPerformed

    private void MaintenanceCustomerIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceCustomerIdComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaintenanceCustomerIdComboActionPerformed

    private void MaintenanceReceivementMonthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceReceivementMonthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaintenanceReceivementMonthComboActionPerformed

    private void MaintenanceBillTaxTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceBillTaxTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaintenanceBillTaxTextActionPerformed

    private void MaintenanceBillTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceBillTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaintenanceBillTotalTextActionPerformed

    private void MaintenanceOptionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceOptionComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaintenanceOptionComboActionPerformed

    private void BillingCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillingCancelButtonActionPerformed
                                     
                                                  
    private static void borrarPanel(JPanel panel) {
        panel.removeAll();
        panel.revalidate();
        panel.repaint();
    }
    private void ShowJPanel(JPanel p){

        p.setSize(1030,750);
        p.setLocation(0,0);
        BillingView.removeAll();
        BillingView.add(p, BorderLayout.CENTER);
        BillingView.revalidate();
        BillingView.repaint();
    }
    
    private void ReadCustomers(){
        String archive = Paths.get("src", "DataBase", "Archivo_CSV_Customers.csv").toString();
        try {
            reader = new BufferedReader(new FileReader(archive));
            while((line = reader.readLine()) != null){
                customer_class temporary_object = new customer_class();
                parts = line.split(",");
                int aux_day = 0;
                int aux_month = 0;
                int aux_year = 0;
                Date birthdate = null;
                for(int i = 0; i < parts.length; i++){
                    switch(i){
                        case 0:
                            temporary_object.setCustomer_id(Integer.parseInt(parts[i]));
                            break;
                        case 1:
                            temporary_object.setCustomer_name(parts[i]);
                            break;
                        case 2:
                            temporary_object.setCustomer_lastname(parts[i]);
                            break;
                        case 3:
                            temporary_object.setCustomer_phone(Integer.parseInt(parts[i]));
                            break;
                        case 4:
                            temporary_object.setCustomer_email(parts[i]);
                            break;
                        case 5:
                            temporary_object.setCustomer_province(parts[i]);
                            break;
                        case 6:
                            temporary_object.setCustomer_canton(parts[i]);
                            break;
                        case 7:
                            temporary_object.setCustomer_district(parts[i]);
                            break;
                        case 8:
                            aux_day = Integer.parseInt(parts[i]);
                            break;
                        case 9:
                            aux_month = Integer.parseInt(parts[i]);
                            break;
                        case 10:
                            aux_year = Integer.parseInt(parts[i]);
                            temporary_object.setCustomer_birthdate(new Date(aux_year-1900, aux_month-1, aux_day));
                            break;
                    }
                }
                customers_list.add(temporary_object);
            }
            reader.close();
            line = null;
            parts = null;
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void ReadItems(){
        String archive = Paths.get("src", "DataBase", "Archivo_CSV_ITEMS.csv").toString();
        try {
            reader = new BufferedReader(new FileReader(archive));
            while((line = reader.readLine()) != null){
                item_class temporary_object = new item_class();
                parts = line.split(",");
                for(int i = 0; i < parts.length; i++){
                    switch(i){
                        case 0:
                            temporary_object.setId_item(Integer.parseInt(parts[i]));
                            break;
                        case 1:
                            temporary_object.setCategory_item(parts[i]);
                            break;
                        case 2:
                            temporary_object.setName_item(parts[i]);
                            break;
                        case 3:
                            temporary_object.setType_item(parts[i]);
                            break;
                        case 4:
                            temporary_object.setSize_item(Double.parseDouble(parts[i]));
                            break;
                        case 5:
                            temporary_object.setBrand_item(parts[i]);
                            break;
                        case 6:
                            temporary_object.setPrice_item(Integer.parseInt(parts[i]));
                            break;
                        case 7:
                            temporary_object.setAmount_item(Integer.parseInt(parts[i]));
                            break;
                    }
                }
                items_list.add(temporary_object);
            }
            reader.close();
            line = null;
            parts = null;
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void ReadMaintenance(){
        String archive = Paths.get("src", "DataBase", "Archivo_CSV_MAINTENANCE.csv").toString();
        try {
            reader = new BufferedReader(new FileReader(archive));
            while((line = reader.readLine()) != null){
                maintenance_class temporary_object = new maintenance_class();
                parts = line.split(",");
                for(int i = 0; i < parts.length; i++){
                    switch(i){
                        case 0:
                            temporary_object.setService_id(Integer.parseInt(parts[i]));
                            break;
                        case 1:
                            temporary_object.setCustomer_id(parts[i]);
                            break;
                        case 2:
                            temporary_object.setBicycle_brand(parts[i]);
                            break;
                        case 3:
                            temporary_object.setBicycle_description(parts[i]);
                            break;
                        case 4:
                            temporary_object.setMaintenance_price(Integer.parseInt(parts[i]));
                            break;
                        case 5:
                            //temporary_object.setBrand_item(parts[i]);
                            break;
                        case 6:
                            //temporary_object.setPrice_item(Integer.parseInt(parts[i]));
                            break;
                        case 7:
                            //temporary_object.setAmount_item(Integer.parseInt(parts[i]));
                            break;
                    }
                }
                maintenance_list.add(temporary_object);
            }
            reader.close();
            line = null;
            parts = null;
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void createIdsItems(){
        int aux = 0;
        for(item_class item:items_list){
            System.out.println(item.getId_item());
            ComboItemsModel.insertElementAt(item.getId_item(), aux);
            ComboItemsModel.setSelectedItem(item.getId_item());
        }
        ItemOptionCombo.setModel(ComboItemsModel);
        ItemOptionCombo.updateUI();
    }
    
    private void createIdsMaintenance(){
        int aux = 0;
        for(maintenance_class item:maintenance_list){
            System.out.println(item.getService_id());
            ComboMaintenanceModel.insertElementAt(item.getService_id(), aux);
            ComboMaintenanceModel.setSelectedItem(item.getService_id());
        }
        ItemOptionCombo.setModel(ComboMaintenanceModel);
        ItemOptionCombo.updateUI();
    }
    
    //Create Flags
    Boolean BillAddFlag = false;
    Boolean BillSearchFlag = false;
    Boolean BillRevokeFlag = false;
    
    //Read CSV
    private BufferedReader reader;
    private String line;
    private String parts[] = null;
    
    //
    DefaultComboBoxModel ComboItemsModel = new DefaultComboBoxModel();   
    DefaultComboBoxModel ComboMaintenanceModel = new DefaultComboBoxModel();
    
    //Create Lists
    ArrayList<customer_class> customers_list = new ArrayList<>();
    ArrayList<item_class> items_list = new ArrayList<>();
    ArrayList<maintenance_class> maintenance_list = new ArrayList<>();
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BillingAddButton;
    private javax.swing.JButton BillingCancelButton;
    private javax.swing.JPanel BillingInputPanel;
    private javax.swing.JPanel BillingInputPanel1;
    private javax.swing.JButton BillingRevokeButton;
    private javax.swing.JButton BillingSearchButton;
    private javax.swing.JPanel BillingView;
    private javax.swing.JLabel BillingWindowSubtitle;
    private javax.swing.JLabel BillingWindowTitle;
    private javax.swing.JLabel BillingWindowTitle1;
    private javax.swing.JLabel BillingWindowTitle2;
    private javax.swing.JButton ItemAcceptButton;
    private javax.swing.JTextField ItemBillIdText;
    private javax.swing.JComboBox<String> ItemBillStateCombo;
    private javax.swing.JTextField ItemBillSubtotalText;
    private javax.swing.JTextField ItemBillTaxText;
    private javax.swing.JTextField ItemBillTotalText;
    private javax.swing.JComboBox<String> ItemCustomerIdCombo;
    private javax.swing.JComboBox<String> ItemOptionCombo;
    private javax.swing.JTextField ItemReceivementDayText;
    private javax.swing.JComboBox<String> ItemReceivementMonthCombo;
    private javax.swing.JTextField ItemReceivementYearText;
    private javax.swing.JButton ItemSearchButton;
    private javax.swing.JButton MaintenanceAcceptButton;
    private javax.swing.JTextField MaintenanceBillIdText;
    private javax.swing.JComboBox<String> MaintenanceBillStateCombo;
    private javax.swing.JTextField MaintenanceBillSubtotalText;
    private javax.swing.JTextField MaintenanceBillTaxText;
    private javax.swing.JTextField MaintenanceBillTotalText;
    private javax.swing.JComboBox<String> MaintenanceCustomerIdCombo;
    private javax.swing.JComboBox<String> MaintenanceOptionCombo;
    private javax.swing.JTextField MaintenanceReceivementDayText;
    private javax.swing.JComboBox<String> MaintenanceReceivementMonthCombo;
    private javax.swing.JTextField MaintenanceReceivementYearText;
    private javax.swing.JButton MaintenanceSearchButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
