/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Classes.*;
import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.*;
import java.io.*;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author jonns
 */

public class ScreenProducts extends javax.swing.JPanel {

    /**
     * Creates new form ScreenProducts
     */
    boolean modify_button;
    boolean delete_button;
    boolean create_button;
    
    public ScreenProducts() {
        initComponents();
        Search_Items.setVisible(false);
        Search_Products.setVisible(false);
        Size.setVisible(false);
        Size_Label.setVisible(false);
        modify_button = false;
        delete_button = false;
        create_button = false;
        
    }
    public boolean getmodify_button(){
        return modify_button;
    }
    
    public boolean getdelete_button(){
        return delete_button;
    }
    
    public boolean getcreate_button(){
        return create_button;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductsView = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Create_Item = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Product_Category = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox<>();
        Size_Label = new javax.swing.JLabel();
        Size = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Modify_Item = new javax.swing.JButton();
        Delete_Item = new javax.swing.JButton();
        Amount = new javax.swing.JTextField();
        Item_Id = new javax.swing.JTextField();
        Item_Name = new javax.swing.JTextField();
        Brand = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Search_Item = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Accept_Item = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Search_Items = new javax.swing.JButton();
        Cancel_Item = new javax.swing.JButton();
        Search_Products = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Accept_Product = new javax.swing.JButton();
        Cancel_Product = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1030, 730));
        setPreferredSize(new java.awt.Dimension(1030, 732));

        ProductsView.setBackground(new java.awt.Color(255, 255, 255));
        ProductsView.setMinimumSize(new java.awt.Dimension(1030, 720));
        ProductsView.setPreferredSize(new java.awt.Dimension(1030, 730));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SalirView.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Category Id:");

        jLabel3.setText("Name:");

        Create_Item.setText("Create Item");
        Create_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_ItemActionPerformed(evt);
            }
        });

        jButton9.setText("Modify");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Delete");

        Product_Category.setEnabled(false);
        Product_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_CategoryActionPerformed(evt);
            }
        });
        Product_Category.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Product_CategoryKeyTyped(evt);
            }
        });

        jLabel5.setText("Item Id:");

        jLabel7.setText("Category Id:");

        jLabel8.setText("Item Name:");

        jLabel9.setText("Type:");

        jLabel10.setText("Amount:");

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bicycle", "Accessories", "Food Supplements" }));
        Type.setEnabled(false);
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        Size_Label.setText("Size:");

        Size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "16", "22", "26", "27", "27.5", "29" }));
        Size.setEnabled(false);
        Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeActionPerformed(evt);
            }
        });

        jLabel12.setText("Brand:");

        jLabel13.setText("Price:");

        Modify_Item.setText("Modify Item");
        Modify_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modify_ItemActionPerformed(evt);
            }
        });

        Delete_Item.setText("Delete Item");
        Delete_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ItemActionPerformed(evt);
            }
        });

        Amount.setEnabled(false);
        Amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AmountKeyTyped(evt);
            }
        });

        Item_Id.setEnabled(false);
        Item_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_IdActionPerformed(evt);
            }
        });
        Item_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Item_IdKeyTyped(evt);
            }
        });

        Item_Name.setAutoscrolls(false);
        Item_Name.setEnabled(false);
        Item_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Item_NameKeyTyped(evt);
            }
        });

        Brand.setEnabled(false);
        Brand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BrandKeyTyped(evt);
            }
        });

        Price.setEnabled(false);
        Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PriceKeyTyped(evt);
            }
        });

        Search_Item.setText("Search Item");
        Search_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ItemActionPerformed(evt);
            }
        });

        jButton20.setText("Create");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Properties:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Products");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Items");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Action:");

        Accept_Item.setText("Accept");
        Accept_Item.setEnabled(false);
        Accept_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accept_ItemActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Search_Items.setText("S");
        Search_Items.setEnabled(false);
        Search_Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ItemsActionPerformed(evt);
            }
        });

        Cancel_Item.setText("Cancel");
        Cancel_Item.setEnabled(false);
        Cancel_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_ItemActionPerformed(evt);
            }
        });

        Search_Products.setText("S");
        Search_Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ProductsActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Properties:");

        Accept_Product.setText("Accept");

        Cancel_Product.setText("Cancel");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Action:");

        javax.swing.GroupLayout ProductsViewLayout = new javax.swing.GroupLayout(ProductsView);
        ProductsView.setLayout(ProductsViewLayout);
        ProductsViewLayout.setHorizontalGroup(
            ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addGroup(ProductsViewLayout.createSequentialGroup()
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductsViewLayout.createSequentialGroup()
                                .addGap(409, 409, 409)
                                .addComponent(jLabel15))
                            .addGroup(ProductsViewLayout.createSequentialGroup()
                                .addGap(443, 443, 443)
                                .addComponent(jLabel19)))
                        .addGap(479, 479, 479)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(Create_Item)
                        .addGap(8, 8, 8)
                        .addComponent(Search_Item)
                        .addGap(6, 6, 6)
                        .addComponent(Modify_Item)
                        .addGap(6, 6, 6)
                        .addComponent(Delete_Item))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(jLabel14))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Item_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(Search_Items, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(Product_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel8)
                        .addGap(21, 21, 21)
                        .addComponent(Item_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Size_Label)
                        .addGap(6, 6, 6)
                        .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12)
                        .addComponent(Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(jLabel13)
                        .addGap(12, 12, 12)
                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12)
                        .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(Accept_Item)
                        .addGap(12, 12, 12)
                        .addComponent(Cancel_Item))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jButton20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(ProductsViewLayout.createSequentialGroup()
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProductsViewLayout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Search_Products, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProductsViewLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18))))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(Accept_Product)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cancel_Product)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProductsViewLayout.setVerticalGroup(
            ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsViewLayout.createSequentialGroup()
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addGap(6, 6, 6)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(10, 10, 10)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Products))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Accept_Product)
                    .addComponent(Cancel_Product))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(15, 15, 15)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Create_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modify_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGap(8, 8, 8)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5))
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Item_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Search_Items))
                .addGap(8, 8, 8)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7))
                    .addComponent(Product_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addComponent(Item_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(Size_Label))))
                .addGap(8, 8, 8)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addComponent(Brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13))
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsViewLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10))
                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ProductsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accept_Item)
                    .addComponent(Cancel_Item)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_ItemActionPerformed
        Reset_Texts();
        Create_Item.setEnabled(true);
        Modify_Item.setEnabled(true);
        Search_Item.setEnabled(true);
        Delete_Item.setEnabled(true);

        Item_Id.setEnabled(false);
        Search_Items.setVisible(false);
        Search_Items.setEnabled(false);
        Product_Category.setEnabled(false);
        Item_Name.setEnabled(false);
        Type.setEnabled(false);
        Type.setSelectedItem("Bicycle");
        Size.setEnabled(false);
        Size.setVisible(false);
        Size_Label.setVisible(false);
        Brand.setEnabled(false);
        Price.setEnabled(false);
        Amount.setEnabled(false);

        Accept_Item.setEnabled(false);
        Cancel_Item.setEnabled(false);
    }//GEN-LAST:event_Cancel_ItemActionPerformed

    private void Accept_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accept_ItemActionPerformed

        String textFromTextField_category = Product_Category.getText();
        if (textFromTextField_category.isEmpty()){
            JOptionPane.showMessageDialog(null, "Product Category Without Text");
            return;
        }
        ///////////////////////////////////////////////
        String textFromTextField_name = Item_Name.getText();
        if (textFromTextField_name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Item Name Without Text");
            return;
        }
        if (textFromTextField_name.trim().equals(textFromTextField_name)) {
        }else {
            JOptionPane.showMessageDialog(null, "Item Name With Spaces At The Ends");
            return;
        }

        ///////////////////////////////////////////////
        String textFromTextField_brand = Brand.getText();
        if (textFromTextField_brand.isEmpty()){
            JOptionPane.showMessageDialog(null, "Brand Without Text");
            return;
        }

        if (textFromTextField_brand.trim().equals(textFromTextField_brand)) {
        }else {
            JOptionPane.showMessageDialog(null, "Brand With Spaces At The Ends");
            return;
        }
        ///////////////////////////////////////////////
        String textFromTextField_price = Price.getText();
        if (textFromTextField_price.isEmpty()){
            JOptionPane.showMessageDialog(null, "Price Without Text");
            return;
        }
        ///////////////////////////////////////////////
        String textFromTextField_amount = Amount.getText();
        if (textFromTextField_amount.isEmpty()){
            JOptionPane.showMessageDialog(null, "Amount Without Text");
            return;
        }

        if (create_button == true) {
            Create_item_products();
            System.out.println("Botón 1 está habilitado. Realizar acciones para boton3.");

        } else if (Search_Item.isEnabled()) {
            System.out.println("Botón 2 está habilitado. Realizar acciones para boton2.");

        } else if (modify_button == true) {
            Modify_item_products(Modify);
            Add_item_products();
            modify_button = false;
            System.out.println("Botón 3 está habilitado. Realizar acciones para boton3.");
        } else if (delete_button == true) {
            System.out.println("Botón 4 está habilitado. Realizar acciones para boton3.");
            boolean result = Delete_item_products();
            if (result == false){
                return;
            }
        }

        Reset_Texts();
        Create_Item.setEnabled(true);
        Modify_Item.setEnabled(true);
        Search_Item.setEnabled(true);
        Delete_Item.setEnabled(true);

        Item_Id.setEnabled(false);
        Search_Items.setVisible(false);
        Search_Items.setEnabled(false);
        Product_Category.setEnabled(false);
        Item_Name.setEnabled(false);
        Type.setEnabled(false);
        Type.setSelectedItem("Bicycle");
        Size.setEnabled(false);
        Size.setVisible(false);
        Size_Label.setVisible(false);
        Brand.setEnabled(false);
        Price.setEnabled(false);
        Amount.setEnabled(false);

        Accept_Item.setEnabled(false);
        Cancel_Item.setEnabled(false);
        modify_button = false;
        delete_button = false;
        create_button = false;

    }//GEN-LAST:event_Accept_ItemActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        // createProduct();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void Search_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ItemActionPerformed
        int opcion = JOptionPane.showOptionDialog(this,"Choose A Search Method",
            "Search",
            JOptionPane.YES_NO_OPTION,   // Tipo de opción (sí/no)
            JOptionPane.QUESTION_MESSAGE, // Tipo de mensaje (pregunta)
            null,                        // Icono personalizado (en este caso, ninguno)
            new Object[]{"ID", "NAME"}, // Texto de los botones
            "Botón 1");                    // Botón predeterminado
        Create_Item.setEnabled(false);
        Modify_Item.setEnabled(false);
        Delete_Item.setEnabled(false);
        Search_Item.setEnabled(false);

        if(opcion == 1){
            Item_Name.setEnabled(true);
        }else{
            Item_Id.setEnabled(true);

        }
        Search_Items.setVisible(true);
        Search_Items.setEnabled(true);
        Cancel_Item.setEnabled(true);
    }//GEN-LAST:event_Search_ItemActionPerformed

    private void PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PriceKeyTyped
        if(Price.getText().length() >= 15){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_PriceKeyTyped

    private void BrandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BrandKeyTyped
        if(Brand.getText().length() >= 15){
            evt.consume();
        }
    }//GEN-LAST:event_BrandKeyTyped

    private void Item_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Item_NameKeyTyped
        if(Item_Name.getText().length() >= 15){
            evt.consume();
        }
    }//GEN-LAST:event_Item_NameKeyTyped

    private void Item_IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Item_IdKeyTyped
        if(Item_Id.getText().length() >= 15){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();

    }//GEN-LAST:event_Item_IdKeyTyped

    private void Item_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item_IdActionPerformed

    private void AmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountKeyTyped
        if(Amount.getText().length() >= 15){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_AmountKeyTyped

    private void Delete_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ItemActionPerformed
        int opcion = JOptionPane.showOptionDialog(this,"Choose A Search Method",
            "Search",
            JOptionPane.YES_NO_OPTION,   // Tipo de opción (sí/no)
            JOptionPane.QUESTION_MESSAGE, // Tipo de mensaje (pregunta)
            null,                        // Icono personalizado (en este caso, ninguno)
            new Object[]{"ID", "NAME"}, // Texto de los botones
            "Botón 1");                    // Botón predeterminado

        Create_Item.setEnabled(false);
        Search_Item.setEnabled(false);
        Modify_Item.setEnabled(false);
        Delete_Item.setEnabled(false);
        delete_button = true;

        if(opcion == 1){
            Item_Name.setEnabled(true);
        }else{
            Item_Id.setEnabled(true);

        }
        Search_Items.setVisible(true);
        Search_Items.setEnabled(true);
        Cancel_Item.setEnabled(true);
    }//GEN-LAST:event_Delete_ItemActionPerformed

    private void Modify_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modify_ItemActionPerformed
        int opcion = JOptionPane.showOptionDialog(this,"Choose A Search Method",
            "Search",
            JOptionPane.YES_NO_OPTION,   // Tipo de opción (sí/no)
            JOptionPane.QUESTION_MESSAGE, // Tipo de mensaje (pregunta)
            null,                        // Icono personalizado (en este caso, ninguno)
            new Object[]{"ID", "NAME"}, // Texto de los botones
            "Botón 1");                    // Botón predeterminado

        Create_Item.setEnabled(false);
        Search_Item.setEnabled(false);
        Delete_Item.setEnabled(false);
        Modify_Item.setEnabled(false);
        modify_button = true;

        if(opcion == 1){
            Item_Name.setEnabled(true);
        }else{
            Item_Id.setEnabled(true);

        }
        Search_Items.setVisible(true);
        Search_Items.setEnabled(true);
        Cancel_Item.setEnabled(true);
    }//GEN-LAST:event_Modify_ItemActionPerformed

    private void SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SizeActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        if ("Bicycle" == Type.getSelectedItem()) {
            Size.setVisible(true);
            Size_Label.setVisible(true);
        } else {
            Size.setVisible(false);
            Size.setSelectedItem("12");
            Size_Label.setVisible(false);

        }

    }//GEN-LAST:event_TypeActionPerformed

    private void Product_CategoryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Product_CategoryKeyTyped
        if(Product_Category.getText().length() >= 15){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_Product_CategoryKeyTyped

    private void Product_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product_CategoryActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //searchProduct();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void Create_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_ItemActionPerformed
        String New_Code = String.valueOf(main_class.items.get(main_class.items.size() - 1).getId_item() + 1);
        Item_Id.setText(New_Code);

        Create_Item.setEnabled(false);
        Modify_Item.setEnabled(false);
        Search_Item.setEnabled(false);
        Delete_Item.setEnabled(false);
        Type.setSelectedItem("Bicycle");
        Product_Category.setEnabled(true);
        Item_Name.setEnabled(true);
        Type.setEnabled(true);
        Size.setEnabled(true);
        Brand.setEnabled(true);
        Price.setEnabled(true);
        Amount.setEnabled(true);
        Accept_Item.setEnabled(true);
        Cancel_Item.setEnabled(true);
        create_button = true;

    }//GEN-LAST:event_Create_ItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        borrarPanel(new ScreenProducts());
        ShowJPanel(new ScreenMain());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SalirView.png")));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SalirView2.png")));
    }//GEN-LAST:event_jButton1MouseEntered

    private void Search_ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ItemsActionPerformed

        String textFromTextField_id = Item_Id.getText();
        String textFromTextField_name = Item_Name.getText();
        int id_item = 0;
        String item_name = "f";
        Modify = null;
        if (textFromTextField_id.isEmpty() && textFromTextField_name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Item Code Without Text");
            return;
        }
        if  (!textFromTextField_id.isEmpty()){
            id_item = Integer.parseInt(textFromTextField_id);
        }
        if  (!textFromTextField_name.isEmpty()){
            item_name = String.valueOf(textFromTextField_name);
        }
        Boolean flag_found = false;

        //System.out.println(main_class.products.get(0));
        for (int i = 0; i < main_class.items.size(); i++) {
            item_class item = main_class.items.get(i);

            if(id_item == item.getId_item() || item_name.equals(item.getName_item())){
                JOptionPane.showMessageDialog(this, "Found");
                flag_found = true;
                System.out.println("Id_product:" + item.getId_item());
                Item_Id.setText(String.valueOf(item.getId_item()));
                Product_Category.setText(String.valueOf(item.getCategory_item()));
                Item_Name.setText(item.getName_item());
                Type.setSelectedItem(item.getType_item());
                if ("Bicycle" == Type.getSelectedItem()){
                    Size.setVisible(true);
                    Size_Label.setVisible(true);
                }
                if (modify_button == true){
                    Modify = item;
                    Item_Id.setEnabled(false);
                    Search_Items.setEnabled(false);
                    Product_Category.setEnabled(true);
                    Item_Name.setEnabled(true);
                    Type.setEnabled(true);
                    Size.setEnabled(true);
                    Brand.setEnabled(true);
                    Price.setEnabled(true);
                    Amount.setEnabled(true);
                    Accept_Item.setEnabled(true);
                    Cancel_Item.setEnabled(true);
                }

                Size.setSelectedItem(String.valueOf(item.getSize_item()));
                Brand.setText(item.getBrand_item());
                Price.setText(String.valueOf(item.getPrice_item()));
                Amount.setText(String.valueOf(item.getAmount_item()));
                Accept_Item.setEnabled(true);
                Cancel_Item.setEnabled(true);
                Search_Items.setEnabled(false);

                break;
            }
        }
        if(flag_found == false){
            JOptionPane.showMessageDialog(null, "Not Found");
        }
    }//GEN-LAST:event_Search_ItemsActionPerformed

    private void Search_ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ProductsActionPerformed
        JOptionPane.showMessageDialog(this,"xd");
    }//GEN-LAST:event_Search_ProductsActionPerformed
     

    
    
        private void Reset_Texts(){
        Component[] components = ProductsView.getComponents();
        for (Component component : components) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            }
        }
    }
    
    
    private void Add_item_products(){
        String archive = Paths.get("src", "DataBase", "Archivo_CSV_ITEMS.csv").toString();
        FileWriter fw = null;
        PrintWriter pw = null;
        
        try{ 
            fw = new FileWriter(archive);
            pw = new PrintWriter(fw);
            for(item_class i: main_class.items){
                String line = i.getId_item() + "," + i.getCategory_item() + "," + i.getName_item() + "," + i.getType_item() + "," + i.getSize_item() + "," + i.getBrand_item() + "," + i.getPrice_item() + "," + i.getAmount_item();
                pw.println(line);
            }
            
        }catch (Exception ex) {
            ex.printStackTrace();
        }
        finally{
            try{
                if(fw != null){
                    fw.close();
            }
            }catch(Exception ex){
                    ex.printStackTrace();
            }      
        }
    }
    


    private boolean Delete_item_products(){
        for(int i = 0; i < main_class.items.size(); i++){
            int Id = Integer.parseInt(Item_Id.getText());
            if(main_class.items.get(i).getId_item() == Id){
                int result = JOptionPane.showConfirmDialog(this, "Delete", "Confirmation", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION){
                    main_class.items.remove(i);
                    JOptionPane.showMessageDialog(this,"Removed");
                    Add_item_products();
                    return true;
                }else{
                    JOptionPane.showMessageDialog(this,"Cancelled");
                    return false;
                }
            }
        }
        return false;
    }
    
    private void Create_item_products(){
        int create_id_item;
        int create_category_item;
        String create_name_item;
        String create_type_item;
        Double create_size_item;
        String create_brand_item;
        int create_price_item;
        int create_amount_item;
        Boolean register = false;
            
            
        create_id_item = Integer.parseInt(Item_Id.getText());
        create_category_item = Integer.parseInt(Product_Category.getText());
        create_name_item = Item_Name.getText();
        create_type_item = String.valueOf(Type.getSelectedItem());
        create_size_item = Double.valueOf(String.valueOf(Size.getSelectedItem()));
        create_brand_item = Brand.getText();
        create_price_item = Integer.parseInt(Price.getText());
        create_amount_item = Integer.parseInt(Amount.getText());
          if(create_type_item != "Bicycle"){
             create_size_item = 0.0;}

         for(item_class A: main_class.items){
            if(A.getName_item().equals(create_name_item)){
                register = true;
                break;}         
            }
            
            if(register){
                JOptionPane.showMessageDialog(this,"This Name Already Exists ");  
                return;
            }else{
                item_class item = new item_class();
                item.setId_item(create_id_item);
                item.setCategory_item(create_category_item);
                item.setName_item(create_name_item);
                item.setType_item(create_type_item);
                item.setSize_item(create_size_item);
                item.setBrand_item(create_brand_item);
                item.setPrice_item(create_price_item);
                item.setAmount_item(create_amount_item);
                main_class.items.add(item);
                Add_item_products();
                JOptionPane.showMessageDialog(this, "Item Added Successfully");
            }
    }
    
    private void Modify_item_products(item_class Modify){
        int modify_id_item;
        int modify_category_item;
        String modify_name_item;
        String modify_type_item;
        Double modify_size_item;
        String modify_brand_item;
        int modify_price_item;
        int modify_amount_item;
        Boolean register = false;
            
            
        modify_id_item = Integer.parseInt(Item_Id.getText());
        modify_category_item = Integer.parseInt(Product_Category.getText());
        modify_name_item = Item_Name.getText();
        modify_type_item = String.valueOf(Type.getSelectedItem());
        modify_size_item = Double.valueOf(String.valueOf(Size.getSelectedItem()));
        modify_brand_item = Brand.getText();
        modify_price_item = Integer.parseInt(Price.getText());
        modify_amount_item = Integer.parseInt(Amount.getText());
        
        if(modify_type_item != "Bicycle"){
             modify_size_item = 0.0;}

         for (item_class A : main_class.items) {
            if (A.getId_item() == modify_id_item && A.getName_item().equals(modify_name_item)) {
                // El objeto con el mismo id y nombre ya existe
                register = false;
                break;
            }
            // Si no encuentras un objeto con el mismo id, puedes permitir el mismo nombre
            if (A.getId_item() == modify_id_item) {
                register = true;
            }
           }
                     

            if(register){
                JOptionPane.showMessageDialog(this,"This Name Already Exists ");  
                return;
            }else{
                Modify.setId_item(modify_id_item);
                Modify.setCategory_item(modify_category_item);
                Modify.setName_item(modify_name_item);
                Modify.setType_item(modify_type_item);
                Modify.setSize_item(modify_size_item);
                Modify.setBrand_item(modify_brand_item);
                Modify.setPrice_item(modify_price_item);
                Modify.setAmount_item(modify_amount_item);
                JOptionPane.showMessageDialog(this, "Item Modified Successfully");
            }
    }
        
       
   
    private item_class Modify;
    
 
    
       
    private static void borrarPanel(JPanel panel) {
        panel.removeAll();
        panel.revalidate();
        panel.repaint();
    }
    private void ShowJPanel(JPanel p){

        p.setSize(1030,750);
        p.setLocation(0,0);
        ProductsView.removeAll();
        ProductsView.add(p, BorderLayout.CENTER);
        ProductsView.revalidate();
        ProductsView.repaint();  
    }
    
    //private void createProduct(){
        //int id_category = 1;
        //String texto_producto = jTextField4.getText();
        
        //if(texto_producto.equals("")){
            //JOptionPane.showMessageDialog(null, "No ha escrito el nombre");
            
        //} else{
            //texto_producto = texto_producto.trim();
            
            //products_class Producto_nuevo = new products_class();
            //Producto_nuevo.id = id_category;
            //Producto_nuevo.name = texto_producto;
            
            //String num_id = Producto_nuevo.id + "";
            
            //String mensaje_mostrar = "Se creó el producto: " + num_id + " " + Producto_nuevo.name;
        
            //JOptionPane.showMessageDialog(null, mensaje_mostrar);
       // }
    //}
    
    //private void searchProduct(){
        //String texto_producto = jTextField4.getText();
        //String id_category = jTextField3.getText();
        //int id_producto = Integer.parseInt(id_category);
        
        

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept_Item;
    private javax.swing.JButton Accept_Product;
    private javax.swing.JTextField Amount;
    private javax.swing.JTextField Brand;
    private javax.swing.JButton Cancel_Item;
    private javax.swing.JButton Cancel_Product;
    private javax.swing.JButton Create_Item;
    private javax.swing.JButton Delete_Item;
    private javax.swing.JTextField Item_Id;
    private javax.swing.JTextField Item_Name;
    private javax.swing.JButton Modify_Item;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Product_Category;
    private javax.swing.JPanel ProductsView;
    private javax.swing.JButton Search_Item;
    private javax.swing.JButton Search_Items;
    private javax.swing.JButton Search_Products;
    private javax.swing.JComboBox<String> Size;
    private javax.swing.JLabel Size_Label;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables


}
